### ISSUE TITLE
No plugin was found for the platform "SmartHQPlugin" 

### ISSUE THREAD

**Issue by DrakeAnglin** [XVincentX/homebridge-plugin-smarthq#2]
**Describe The Bug:**

After installing the plugin and restarting homebridge the console show a error, and none of the devices are loaded

**To Reproduce:**

- Install using homebridge
- follow config
- restart homebridge

**Expected behavior:**

The SmartHQ plugin should start 

**Logs:**
![image](https://user-images.githubusercontent.com/37958526/196049484-51c3fc6e-a267-4632-a257-c6f4d77400ce.png)

**Plugin Config:**
My info has been removed

![image](https://user-images.githubusercontent.com/37958526/196049542-9251bdfb-30c6-42ca-b413-2d16e80fd043.png)

**Screenshots:**

**Environment:**

* **Plugin Version**:  v0.0.1
* **Homebridge Version**: v1.5
* **Node.js Version**: v16.16.0
* **NPM Version**:  8.11.0
* **Operating System**: Raspbian

**Comment by XVincentX** [comment]
Hey,

it is always great to see people downloading and using my stuff.

At this stage though, the plugin is far away from being ready. While I have been able to successfully command the oven lights and also send and receive data to command the oven to start - I cannot set them up in HomeBridge because HomeKit does not support these accessories.

For instance, the oven thermostat goes way above 100C - this is the limit of the HomeKit thermostat, cause it's for an HVAC system.

As soon as Apple adds more devices (well, assuming they do so) I will finish up this plugin.

**Comment by DrakeAnglin** [comment]
that makes sense. I was excited to see this plugin when i install homebridge this weekend. 

I would also be happy to help develop and/or test if your looking for help! 

Let me know if there are anymore updates on this in the future.

**Comment by XVincentX** [comment]
I do not mind publishing what I have as a NPM package, but all you will be able to do is to turn on and off the oven light

**Comment by DrakeAnglin** [comment]
its a start! that would be better than nothing.

**Comment by XVincentX** [comment]
I did that. You can give it a try and see what happens
